### ISSUE TITLE
Request to Add Perplexity Windows App to Winget Packages

### ISSUE THREAD

**Issue by n8creator** [inulute/perplexity-ai-app#11]
I would like to suggest adding the Perplexity Windows App, currently available on GitHub, to the Winget package repository. Including this application in Winget would significantly improve accessibility for Windows users, making installation and updates more streamlined through simple `winget` commands such as:

- `winget search Perplexity` - to find the app
- `winget install Perplexity` - for quick installation
- `winget upgrade Perplexity` - to keep the app up to date

Here's an example of how it would appear in the terminal:

```sh
$ winget search Perplexity
Name              Id                      Version Match        Source
---------------------------------------------------------------------
Perplexity        inulute.PerplexityApp   1.1.0                winget
```

For reference on how to add a new package, please see:  https://github.com/microsoft/winget-pkgs/issues/new/choose

Thank you for considering this suggestion.

**Comment by inulute** [comment]
Thank you for your suggestion regarding adding the Perplexity Windows App to the Winget package repository.

The reason I'm currently using Pling instead of Winget is to generate a bit of revenue, as donations alone are not sufficient to cover the ongoing costs. Pling allows for some monetization, which helps sustain the development and maintenance of the app.

I hope you understand the reasoning behind this choice. Thanks!
