### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by kaxlabs** [inulute/perplexity-ai-app#12]
Good app but could be made more viable.

- Add settings to boot the app on startup, minimize to tray instead of closing, and start minimized
- Make numpad 6/7 work along with the numbers on top of the keyboard
- Add configurable keybinds
- Add setting to always use Pro searches
- Add a way to return to the "Choose an AI to Navigate" screen
- Add default AI setting (chat/labs) or remember previous AI selection when booting the application

**Comment by heinhuiz** [comment]
+1 for the last suggestion

**Comment by inulute** [comment]
Thank you for the feedback and suggestions!

**Comment by mblais** [comment]
Piggybacking on this thread - I would love to see the following features:
- Multiple tabs (Ctrl+T) and windows (Ctrl+N)
- User CSS (e.g. to adjust the width of the left sidebar)
- "Find" (Ctrl+F) to search current page - this is an important function that a web browser can do, but the app cannot 😢 E.g. viewing a Space with many threads, and I want to scan all threads with a certain word.
 
Thanks for the great app! 😉

**Comment by inulute** [comment]
> Piggybacking on this thread - I would love to see the following features:
> - Multiple tabs (Ctrl+T) and windows (Ctrl+N)
> - User CSS (e.g. to adjust the width of the left sidebar)
> - "Find" (Ctrl+F) to search current page - this is an important function that a web browser can do, but the app cannot 😢 E.g. viewing a Space with many threads, and I want to scan all threads with a certain word.
>  
> Thanks for the great app! 😉



Hey, I appreciate your suggestions! We’re close to finalizing an update, and while we can’t implement these features at the moment, we will certainly consider them for future releases.

Thanks!!

**Comment by inulute** [comment]
Thank you for the detailed feedback and your interest in making Perplexity AI even better!

We’re excited to share that Perplexity AI v3.0.0 includes several updates that align with your suggestions:

Default AI Tool Setting: You can now set a default AI tool, so the app remembers your preference (such as Chat or Labs) and automatically opens to it on startup.
Configurable Keybinds: Customize essential shortcuts, including switching AI modes, minimizing, restoring, and more, directly in the settings.
Minimize to Tray: With this update, you can send the app to the system tray instead of fully closing it, making it quicker to access again when needed.

> Good app but could be made more viable.
> 
> * Add settings to boot the app on startup, minimize to tray instead of closing, and start minimized
> * Make numpad 6/7 work along with the numbers on top of the keyboard
> * Add configurable keybinds
> * Add setting to always use Pro searches
> * Add a way to return to the "Choose an AI to Navigate" screen
> * Add default AI setting (chat/labs) or remember previous AI selection when booting the application

Thank you for the detailed feedback and your interest in making Perplexity AI even better!

We’re excited to share that **Perplexity AI v3.0.0** includes several updates that align with your suggestions:

- **Default AI Tool Setting**: You can now set a default AI tool, so the app remembers your preference (such as Chat or Labs) and automatically opens to it on startup.
- **Configurable Keybinds**: Customize essential shortcuts, including switching AI modes, minimizing, restoring, and more, directly in the settings.
- **Minimize to Tray**: With this update, you can send the app to the system tray instead of fully closing it, making it quicker to access again when needed.

Thanks again for your valuable feedback and support!
